FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# First Catering Ltd blueprint

Allows employees of Bows Formula One to use their existing employee cards in a kiosk to register and top up with money.

## Verify user [/user/{employeeId}]

Allows for verification of a user.

### Verify User exists [GET]

+ Response 200 (application/json)

        User found 
        
+ Response 404 (application/json)
    
        User not found

## Register user [/user]

Register a user by sending all the following information.

### Register a user [POST]

+ Request (application/json)

        {
            "employeeId"   : "6hdy74jfi819f6d3",
            "name"         : "William Eyre",
            "email"        : "william@email.com",
            "mobileNumber" : 12345678901,
            "pin"          : 1234
        }

+ Response 200 (application/json)

## Authentication [/authenticate]


### Authenticate User [POST]

Returns a JWT to the front end that is then put into the header of all subsequent request to authenticate the user.
The JWT will have a expiry time of five minutes. 

+ Request (application/json)

        {
           "employeeId" : "6hdy74jfi819f6d3"
           "pin" : 1234
        }

+ Response 200 (application/json)
    

    + Body

            {
                "token" : "eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE1MzMxMzIyMjQsImV4cCI6MTUzMzEzNTgyNCwiaWRlbnRpdHkiOiIxMjM0NTYiLCJuYW1lIjoiV2lsbCBFeXJlIn0.0A3M79Q3o6zLrPGuWlhhWisUAtuobd8QQ2GldZm0j8hULHMLRcmsgVFxFKfwDBqXr-TeNAQyCUXH36wz8wRAxg"
            }
               
               
               


## Purchase item [/purchase/{employeeId}]

Balance will be in pennies to make currency hanlding easier.

### Purchase item [PATCH]


  
+ Request (application/json) 


    + Headers


                X-AUTHORZATION : eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE1MzMxMzIyMjQsImV4cCI6MTUzMzEzNTgyNCwiaWRlbnRpdHkiOiIxMjM0NTYiLCJuYW1lIjoiV2lsbCBFeXJlIn0.0A3M79Q3o6zLrPGuWlhhWisUAtuobd8QQ2GldZm0j8hULHMLRcmsgVFxFKfwDBqXr-TeNAQyCUXH36wz8wRAxg



   + Body

            {
                "purchaseTotal" : 200
            }
            
        
+ Response 200 (application/json) 


    + Body

            {
                "balance" : 1000
            }
        



## Top up card [/topup/{employeeId}]

Balance will be in pennies to make currency hanlding easier.

### Top up card [PATCH]


    
+ Request (application/json) 


     + Headers


            X-AUTHORZATION : eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE1MzMxMzIyMjQsImV4cCI6MTUzMzEzNTgyNCwiaWRlbnRpdHkiOiIxMjM0NTYiLCJuYW1lIjoiV2lsbCBFeXJlIn0.0A3M79Q3o6zLrPGuWlhhWisUAtuobd8QQ2GldZm0j8hULHMLRcmsgVFxFKfwDBqXr-TeNAQyCUXH36wz8wRAxg
        

    + Body

            {
                "debitAmount" : 200
            }
            
            

+ Response 200 (application/json)
    

    + Body

            {
                "balance" : 1000
            }